sudo: required
dist: trusty

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "node"

matrix:
  fast_finish: true

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - echo '{"AWSAccessKeyId":"","AWSSecretKey":""}' >> aws-keys.json
  - npm install -g grunt-cli
  - npm install

cache:
  directories:
    - node_modules
