sudo: required
dist: trusty
language: node_js
node_js:
- 6
branches:
  only:
  - master
install:
- echo '{"AWSAccessKeyId":"","AWSSecretKey":""}' >> aws-keys.json
- npm install -g grunt-cli
- yarn
script:
- yarn test
cache:
  directories:
  - node_modules
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/78a9fadbca7e126c06bc
    on_success: change
    on_failure: always
    on_start: never
